version: '3.9'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=postgres

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
